import test from 'node:test';import assert from 'node:assert/strict';import * as fs from 'node:fs/promises';import path from 'node:path';import vm from 'node:vm';
import {apply as hostApply} from '../lib/index.js';import {SOURCE,addReference,removeReference,detectOffset,createDshPlugin} from '../src/dsh-client.js';import {fixture} from './helpers.mjs';
function editor(legacy=false){
 let snapshot={draft:'start OTHER tail ',draftRev:1,phase:'plain',occurrences:[{offset:6,length:legacy?undefined:5,source:'other',ref:'other',label:'OTHER'}]};if(legacy)snapshot.draft='start \uFFFC tail ';
 const detectToClip=x=>{let clip=x;for(const o of snapshot.occurrences){const d=detectOffset(snapshot,o.offset);if(d<x)clip+=(o.length??1)-1;}return clip;};
 function edit(text,span,ref){assert.equal(span.draftRev,snapshot.draftRev);const start=detectToClip(span.start),end=detectToClip(span.end),delta=text.length-(end-start);const occ=snapshot.occurrences.filter(o=>o.offset<start||o.offset>=end).map(o=>({...o,offset:o.offset>=end?o.offset+delta:o.offset}));if(ref)occ.push({...ref,offset:start,length:legacy?undefined:text.length});occ.sort((a,b)=>a.offset-b.offset);snapshot={...snapshot,draft:snapshot.draft.slice(0,start)+text+snapshot.draft.slice(end),draftRev:snapshot.draftRev+1,occurrences:occ};return true;}
 return{state:{getSnapshot:()=>snapshot},setDraft(){throw new Error('WHOLE-DRAFT EDIT MUST NOT RUN');},insertReference(ref,span){return edit(legacy?'\uFFFC':ref.clipboardText,span,ref);},editSpan:request=>edit(request.text,request.span),setPhase:p=>snapshot.phase=p};
}
for(const legacy of [false,true])test(`safe reference add/remove preserves foreign chips (${legacy?'legacy one-character':'modern clipboard offsets'})`,()=>{const input=editor(legacy),before=input.state.getSnapshot().draft;const r={id:'r',label:'folder',selection:{folder:true}};addReference(input,r);addReference(input,r);assert.equal(input.state.getSnapshot().occurrences.length,2);removeReference(input,r,input.editSpan);assert.equal(input.state.getSnapshot().draft,before);assert.equal(input.state.getSnapshot().occurrences[0].source,'other');});
test('locked input and unavailable edit event fail without rewriting draft',()=>{const input=editor(),r={id:'r',label:'f',selection:{}};input.setPhase('submitting');assert.throws(()=>addReference(input,r),{code:'locked'});input.setPhase('plain');addReference(input,r);assert.throws(()=>removeReference(input,r),{code:'edit-contract'});assert.equal(input.state.getSnapshot().occurrences.length,2);});
test('DSH host route lifecycle and late optional workspace capability',async t=>{const f=await fixture(t),effects=[];let route,disposed=false,controller;const ctx={get:name=>({webServer:{register:r=>{route=r;return()=>disposed=true;}},sessions:{get:()=>({header:{cwd:f.dirs.a}})},workspaceController:controller})[name],effect:fn=>effects.push(fn())};const store=hostApply(ctx,{storageRoot:path.join(f.root,'host')});await store.ready;assert.equal(route.kind,'prefix');assert.equal(typeof store.registerWorkspace,'undefined');controller={create:async({path})=>({workspace:{workspaceId:'w',path}})};assert.equal(typeof store.registerWorkspace,'function');assert.equal((await store.registerExisting(f.dirs.a)).workspace.workspaceId,'w');effects.forEach(fn=>fn());assert.equal(disposed,true);});
test('client refuses incompatible contracts before touching DOM',()=>{const plugin=createDshPlugin({createElement(){}},'');assert.throws(()=>plugin.apply({get:()=>null}),{code:'client-contract'});});
test('built browser artifact registers the original package identity and has no external bundle dependencies',async()=>{const source=await fs.readFile(new URL('../lib/client.js',import.meta.url),'utf8');let registration;vm.runInNewContext(source,{window:{__ModuleLoader__:{load:value=>registration=value}},console});assert.equal(registration.id,'dsh-multimedia-webui-input');const requires=[];const plugin=registration.factory(name=>{requires.push(name);return{createElement(){}};});assert.deepEqual(requires,['react']);assert.equal(typeof plugin.apply,'function');assert.ok(Array.from(plugin.inject).includes('inputTriggers'));});

test('cold persisted sessions resolve through official inspection without activation',async t=>{const f=await fixture(t),effects=[];const ctx={get:key=>({webServer:{register:()=>()=>{}},sessions:{get:()=>undefined},sessionController:{inspect:async()=>({header:{cwd:f.dirs.a}})}})[key],effect:fn=>effects.push(fn())};const store=hostApply(ctx,{storageRoot:path.join(f.root,'cold-host')});await store.ready;assert.equal(await store.sessionRoot('cold'),f.dirs.a);effects.forEach(fn=>fn());});
