import test from 'node:test';import assert from 'node:assert/strict';import * as fs from 'node:fs/promises';import path from 'node:path';import {Readable,PassThrough} from 'node:stream';import {createHash} from 'node:crypto';
import {fixture,plan,upload,code,until} from './helpers.mjs';
test('real streamed bytes, SHA-256, nested structure and empty directories',async t=>{
 const f=await fixture(t),p=plan();assert.deepEqual(await fs.readdir(f.dirs.a),[]);
 const r=await upload(f.store,p);assert.equal(await fs.readFile(path.join(r.root,'project/a.txt'),'utf8'),'hello');assert.equal((await fs.stat(path.join(r.root,'project/vacant'))).isDirectory(),true);assert.equal((await fs.stat(path.join(r.root,'project/empty.txt'))).size,0);assert.equal(r.files[0].sha256,createHash('sha256').update('hello').digest('hex'));assert.equal(JSON.parse(await fs.readFile(r.manifest)).owner,'better-attach/v2');
 const {handle}=await f.store.openFile(r.id,'a',0);assert.equal(await handle.readFile('utf8'),'hello');await handle.close();
});
test('incomplete commit does not publish a final directory',async t=>{const f=await fixture(t),p=plan();await f.store.create(p.request);await assert.rejects(f.store.commit(p.request.id,'a'),code('incomplete'));assert.equal((await f.store.get(p.request.id,'a')).status,'staging');assert.equal(f.store.sealing.size,0);});
test('create and commit idempotency plus no postcommit mutation',async t=>{const f=await fixture(t),p=plan();const r=await upload(f.store,p);assert.equal((await f.store.create(p.request)).status,'committed');assert.deepEqual(await f.store.commit(r.id,'a'),r);await assert.rejects(f.store.put(r.id,'a',0,Readable.from(['hello'])),code('batch-state'));const changed=structuredClone(p.request);changed.files[0].size++;await assert.rejects(f.store.create(changed),code('idempotency-conflict'));});
test('partial-size failure and retry leave no partial accepted file',async t=>{const f=await fixture(t),p=plan();await f.store.create(p.request);await assert.rejects(f.store.put(p.request.id,'a',0,Readable.from(['hel'])),code('length-mismatch'));await assert.rejects(f.store.put(p.request.id,'a',0,Readable.from(['toolong'])),code('length-mismatch'));assert.deepEqual((await f.store.create(p.request)).received,[]);await f.store.put(p.request.id,'a',0,Readable.from(['hello']));assert.deepEqual((await f.store.create(p.request)).received,[0]);});
test('received-file retry compares content, not name or size alone',async t=>{const f=await fixture(t),p=plan();await f.store.create(p.request);await f.store.put(p.request.id,'a',0,Readable.from(['hello']));await f.store.put(p.request.id,'a',0,Readable.from(['hello']));await assert.rejects(f.store.put(p.request.id,'a',0,Readable.from(['world'])),code('content-conflict'));});
test('session ownership and changed cwd reject commit',async t=>{const f=await fixture(t),p=plan();await f.store.create(p.request);await assert.rejects(f.store.get(p.request.id,'b'),code('session-mismatch'));f.dirs.a=f.dirs.b;await assert.rejects(f.store.put(p.request.id,'a',0,Readable.from(['hello'])),code('workspace-changed'));await assert.rejects(f.store.commit(p.request.id,'a'),code('workspace-changed'));});
test('workspace has dedicated scope independent of an active conversation',async t=>{const f=await fixture(t),p=plan({target:'workspace',sessionId:'@workspace-import'});const r=await upload(f.store,p);assert.ok(r.workspace.workspaceId);assert.equal(r.workspace.path,path.join(r.root,'project'));assert.ok(r.root.startsWith(f.store.workspaceRoot));assert.equal(f.calls,1);await f.store.commit(r.id,'@workspace-import');assert.equal(f.calls,1);assert.deepEqual(await fs.readdir(f.dirs.a),[]);});
test('workspace scope cannot be used to smuggle a conversation attachment',async t=>{const f=await fixture(t);for(const opt of [{target:'conversation',sessionId:'@workspace-import'},{target:'workspace',sessionId:'a'}])await assert.rejects(f.store.create(plan(opt).request),code('workspace-scope'));});
test('workspace requires one folder and capability, never fake success',async t=>{const f=await fixture(t),p=plan({target:'workspace',sessionId:'@workspace-import',names:['a.txt'],contents:['x'],directories:[]});await assert.rejects(f.store.create(p.request),code('workspace-folder'));f.store.registerWorkspace=undefined;await assert.rejects(f.store.create(plan({target:'workspace',sessionId:'@workspace-import'}).request),code('workspace-unavailable'));});
test('registration failure after copy can retry without duplicating files',async t=>{const f=await fixture(t);const real=f.store.registerWorkspace;let fail=true;f.store.registerWorkspace=async p=>{if(fail){fail=false;throw new Error('fixture registry offline');}return real(p);};const p=plan({target:'workspace',sessionId:'@workspace-import'});await assert.rejects(upload(f.store,p),/fixture registry offline/);assert.equal((await f.store.get(p.request.id,p.request.sessionId)).status,'registering');const r=await f.store.commit(p.request.id,p.request.sessionId);assert.equal(await fs.readFile(path.join(r.root,'project/a.txt'),'utf8'),'hello');assert.equal(f.registry.size,1);});
test('restart reloads metadata, histories and completed receipt',async t=>{const f=await fixture(t),p=plan();const r=await upload(f.store,p);const s=f.restart();assert.equal((await s.history('a'))[0].id,r.id);assert.deepEqual(await s.history('b'),[]);assert.deepEqual(await s.commit(r.id,'a'),r);});
test('two files upload concurrently and commit refuses an active writer',async t=>{const f=await fixture(t),p=plan();await f.store.create(p.request);const slow=new PassThrough();const write=f.store.put(p.request.id,'a',0,slow);await until(()=>f.store.writes.size===1);await f.store.put(p.request.id,'a',1,Readable.from([]));await assert.rejects(f.store.commit(p.request.id,'a'),code('upload-in-progress'));slow.end('hello');await write;assert.equal((await f.store.commit(p.request.id,'a')).files.length,2);});
test('cancel aborts an actual stream and deletes only its pending directory',async t=>{const f=await fixture(t),p=plan();await f.store.create(p.request);const slow=new PassThrough();slow.on('error',()=>{});const write=f.store.put(p.request.id,'a',0,slow);const rejection=assert.rejects(write);await until(()=>f.store.writes.size===1);await f.store.cancel(p.request.id,'a');await rejection;const b=await f.store.get(p.request.id,'a');assert.equal(b.status,'cancelled');await assert.rejects(fs.stat(b.stage),{code:'ENOENT'});await assert.rejects(f.store.create(p.request),code('cancelled'));});
test('late upload admission cannot race a commit sealing a batch',async t=>{const f=await fixture(t),p=plan();await f.store.create(p.request);const original=f.store.pinned.bind(f.store);let release;f.store.pinned=async b=>{await original(b);await new Promise(r=>release=r);};const put=f.store.put(p.request.id,'a',0,Readable.from(['hello']));await until(()=>!!release);f.store.sealing.add(p.request.id);release();await assert.rejects(put,code('batch-state'));assert.equal(f.store.writes.size,0);});
test('symlink storage ancestor and committed file substitution rejected',async t=>{
 if(process.platform==='win32'){t.skip('Symlink creation requires privileges on Windows');return;}
 const f=await fixture(t),outside=path.join(f.root,'outside');await fs.mkdir(outside);await fs.symlink(outside,path.join(f.dirs.a,'.dsh'));
 await assert.rejects(f.store.create(plan().request),code('symlink'));await fs.unlink(path.join(f.dirs.a,'.dsh'));
 const r=await upload(f.store,plan());await fs.writeFile(path.join(outside,'secret'),'secret');const file=path.join(r.root,r.files[0].path);await fs.unlink(file);await fs.symlink(path.join(outside,'secret'),file);await assert.rejects(f.store.openFile(r.id,'a',0));assert.equal(await fs.readFile(path.join(outside,'secret'),'utf8'),'secret');
});
test('cleanup is explicit and isolated from original files, other sessions and workspace copies',async t=>{const f=await fixture(t);const original=path.join(f.dirs.a,'original.txt');await fs.writeFile(original,'keep');const a=await upload(f.store,plan()),b=await upload(f.store,plan({sessionId:'b'})),w=await upload(f.store,plan({sessionId:'@workspace-import',target:'workspace'}));await assert.rejects(f.store.cleanSession('a','yes'),code('confirmation'));assert.equal((await f.store.cleanSession('a','DELETE ATTACHMENTS')).files,2);await assert.rejects(fs.stat(a.root),{code:'ENOENT'});assert.ok(await fs.stat(b.root));assert.ok(await fs.stat(w.root));assert.equal(await fs.readFile(original,'utf8'),'keep');assert.deepEqual(await f.store.history('a'),[]);});
test('pending capacity and stale TTL cleanup never auto-delete committed files',async t=>{const f=await fixture(t,{maxActive:1,ttl:10}),p=plan();await f.store.create(p.request);await assert.rejects(f.store.create(plan().request),code('capacity'));assert.equal((await f.store.cleanAbandoned(Date.now()+1000)).count,1);const r=await upload(f.store,plan());await f.store.cleanAbandoned(Date.now()+100000);assert.ok(await fs.stat(r.root));});
test('explicit host directory registration does not copy it',async t=>{const f=await fixture(t);await fs.writeFile(path.join(f.dirs.a,'original'),'untouched');const result=await f.store.registerExisting(f.dirs.a);assert.equal(result.workspace.path,await fs.realpath(f.dirs.a));assert.deepEqual(await fs.readdir(f.store.workspaceRoot),[]);await assert.rejects(f.store.registerExisting('relative'),code('absolute-path'));await assert.rejects(f.store.registerExisting(path.join(f.dirs.a,'original')),code('not-directory'));});
