/** Real-browser verification against an independently running DSH host. */
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {fixtureTree,dispatchDrop,safeOrigin} from './record.mjs';
const url=safeOrigin(process.env.DSH_URL||'http://127.0.0.1:3188');const out=path.resolve('work/browser-qa');await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({storageState:process.env.RECORD_STORAGE_STATE,viewport:{width:1280,height:800},locale:'zh-CN'});const page=await context.newPage(),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const run=async(name,fn)=>{await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);};
try{await page.goto(url.href);await page.locator('[data-better-attach-toolbar]').waitFor();
const settings=async()=>page.getByRole('button',{name:/^(附件设置|Attachment settings)$/}).click();const close=async()=>page.locator('.ba-dialog').last().locator('.ba-dialog-head .ba-icon').click();
await run('settings persist across reload',async()=>{await settings();await page.locator('input[value="path"]').check();await close();await page.reload();await settings();assert.equal(await page.locator('input[value="path"]').isChecked(),true);await page.locator('input[value="copy"]').check();await close();});
const tree=await fixtureTree(path.resolve(process.env.RECORD_FIXTURES||'recording/fixtures'));
const drop=async(nodes)=>{const box=await page.locator('[data-better-attach-toolbar]').boundingBox();await page.evaluate(dispatchDrop,{x:box.x+30,y:box.y+12,tree:nodes,phase:'drop'});await page.locator('.ba-dialog').waitFor();};
await run('directory enumeration includes children and empty directories',async()=>{await drop(tree.filter(n=>n.name==='folder'));await page.getByRole('button',{name:'folder/src/answer.txt',exact:true}).waitFor();await page.getByRole('button',{name:'folder/empty',exact:true}).waitFor();});
await run('text preview reads original bytes',async()=>{await page.getByRole('button',{name:'folder/src/answer.txt',exact:true}).click();assert.match(await page.locator('.ba-text').innerText(),/纸舟沿河行/);await close();});
await run('folder is a single composer card and can be removed',async()=>{await page.locator('.ba-dialog .ba-primary').click();await page.locator('.ba-card').last().waitFor();const card=page.locator('.ba-card').last();assert.match(await card.innerText(),/folder/);await card.getByRole('button',{name:/^(移除|Remove)$/}).click();await card.waitFor({state:'detached'});});
await run('failed upload retains draft and retry saves real bytes',async()=>{await drop(tree.filter(n=>n.name==='note.md'));await page.locator('.ba-dialog .ba-primary').click();await page.locator('.ba-card').last().waitFor();const fail=route=>route.request().method()==='PUT'?route.abort('connectionreset'):route.continue();await page.route('**/community-multimedia-webui-input/v2/batches/**/files/*',fail);await page.getByRole('button',{name:/^(发送消息|Send message)$/}).click();await page.getByRole('button',{name:/^(重试保存|Retry saving)$/}).waitFor();await page.screenshot({path:path.join(out,'retry.png')});await page.unroute('**/community-multimedia-webui-input/v2/batches/**/files/*',fail);await page.getByRole('button',{name:/^(重试保存|Retry saving)$/}).click();await page.locator('.ba-card[data-status="committed"]').waitFor();await page.locator('.ba-card').last().getByRole('button',{name:/^(移除|Remove)$/}).click();});
await run('path validation preserves dialog on missing file',async()=>{await settings();await page.locator('input[value="path"]').check();await close();await page.getByRole('button',{name:/^(添加文件|Attach files)$/}).click();await page.locator('.ba-dialog .ba-search').fill('/nonexistent/better-attach-check.txt');await page.locator('.ba-dialog .ba-primary').click();await page.locator('.ba-dialog .ba-error').waitFor({state:'visible'});await close();});
await run('appearance and narrow layouts',async()=>{await settings();for(const theme of ['plain','official','character']){await page.locator(`input[value="${theme}"]`).check();assert.equal(await page.locator('html').getAttribute('data-ba-theme'),theme);}await page.locator('input[value="plain"]').check();await page.locator('input[value="copy"]').check();await page.setViewportSize({width:390,height:844});const box=await page.locator('.ba-dialog').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=391);await page.screenshot({path:path.join(out,'mobile-settings.png')});await close();await page.setViewportSize({width:1280,height:800});});
await run('native dark colors reach attachment panels',async()=>{await settings();const light=await page.locator('.ba-dialog').evaluate(el=>getComputedStyle(el).backgroundColor);await page.emulateMedia({colorScheme:'dark'});await page.waitForTimeout(250);const dark=await page.locator('.ba-dialog').evaluate(el=>getComputedStyle(el).backgroundColor);assert.notEqual(dark,light);await page.screenshot({path:path.join(out,'dark-settings.png')});await close();});
await run('no uncaught browser errors',async()=>assert.deepEqual(errors,[]));
}finally{await fs.writeFile(path.join(out,'report.json'),JSON.stringify({realDSH:true,syntheticDrop:true,checks,errors},null,2));await browser.close();}
