import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
// Intentionally small deterministic bundler: these owned sources have only single-line relative imports.
const inputs=['lib/policy.js','lib/preferences.js','lib/intake.js','lib/client-api.js','lib/native-drop-client.js','lib/ui.js','src/dsh-client.js'];
const readText=async file=>(await fs.readFile(path.join(root,file),'utf8')).replace(/\r\n?/g,'\n');
const contents=[];
for(const file of inputs){const raw=await readText(file);contents.push(`\n// ---- ${file} ----\n`+raw.replace(/^import .*;\r?\n/gm,'').replace(/^export (?=(?:async )?(?:function|class|const|let)\b)/gm,''));}
const logo=Buffer.from(await readText('assets/logo.svg'));
const character=await fs.readFile(path.join(root,'assets/character.jpg'));
const css=(await readText('lib/ui.css'))+'\n:root{--ba-character:url(data:image/jpeg;base64,'+character.toString('base64')+');--ba-logo:url(data:image/svg+xml;base64,'+logo.toString('base64')+')}';
const text=`/* Better Attach 0.3.0-rc.6; generated by scripts/build.mjs; no runtime dependencies bundled. */\nwindow.__ModuleLoader__.load({id:'dsh-multimedia-webui-input',factory:require=>{\n'use strict';\n${contents.join('\n')}\nreturn createDshPlugin(require('react'),${JSON.stringify(css)});\n}});\n`;
await fs.writeFile(path.join(root,'lib/client.js'),text);
console.log(`Built lib/client.js (${Buffer.byteLength(text)} bytes), ${inputs.length} owned modules; React is provided by DSH.`);
