import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
// Intentionally small deterministic bundler: these owned sources have only single-line relative imports.
const inputs=['lib/policy.js','lib/preferences.js','lib/intake.js','lib/client-api.js','lib/ui.js','src/dsh-client.js'];
const contents=[];
for(const file of inputs){const raw=await fs.readFile(path.join(root,file),'utf8');contents.push(`\n// ---- ${file} ----\n`+raw.replace(/^import .*;\r?\n/gm,'').replace(/^export (?=(?:async )?(?:function|class|const|let)\b)/gm,''));}
const character=await fs.readFile(path.join(root,'assets/character.jpg'));
const css=(await fs.readFile(path.join(root,'lib/ui.css'),'utf8'))+'\n:root{--ba-character:url(data:image/jpeg;base64,'+character.toString('base64')+')}';
const text=`/* Better Attach 0.3.0-rc.1; generated by scripts/build.mjs; no runtime dependencies bundled. */\nwindow.__ModuleLoader__.load({id:'dsh-multimedia-webui-input',factory:require=>{\n'use strict';\n${contents.join('\n')}\nreturn createDshPlugin(require('react'),${JSON.stringify(css)});\n}});\n`;
await fs.writeFile(path.join(root,'lib/client.js'),text);
console.log(`Built lib/client.js (${Buffer.byteLength(text)} bytes), ${inputs.length} owned modules; React is provided by DSH.`);
